grails:
    profile: web-plugin
    codegen:
        defaultPackage: nucleus

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    groovy:
        template:
            check-template-location: false

---
dataSource:
    pooled: true
    driverClassName: "org.h2.Driver"
    username: 'root'
    password: 'causecode.11'
    dialect: "org.hibernate.dialect.H2Dialect"

hibernate:
    cache:
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory' # Hibernate

---
environments:
    development:
        dataSource:
            dbCreate: 'update' # one of 'create', 'create-drop', 'update', 'validate', ''
            #url: 'jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
            url: 'jdbc:h2://localhost:3306/nucleus'
    test:
        dataSource:
            dbCreate: 'update'
            #url: 'jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
            url: 'jdbc:h2://localhost:3306/nucleus_t'
    production:
        dataSource:
            dbCreate: 'update'
            url: 'jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
            properties:
                maxActive: -1
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                validationQuery: 'SELECT 1'
                jdbcInterceptors: 'ConnectionState'